### ISSUE TITLE
Wireframe Stream Landing Page

### ISSUE THREAD

**Issue by maznan** [muthesius/muid-site#1]
![wf_stream_01](https://cloud.githubusercontent.com/assets/23743879/20930728/e190b376-bbce-11e6-9fa1-be4c99ae26ee.jpg)
![wf_stream_02](https://cloud.githubusercontent.com/assets/23743879/20930733/e48f9056-bbce-11e6-963c-b9be02815b96.jpg)

**Comment by jnslxndr** [comment]
2nd image top right!
![e48f9056-bbce-11e6-963c-b9be02815b96 kopie](https://cloud.githubusercontent.com/assets/9602/21098659/909b5ef8-c06a-11e6-8d8c-ab2b6c29b070.jpg)
